# Nombre de la aplicación
spring.application.name=SaveUp

# Puerto en el que correrá el servidor del backend
server.port=8080

# --- Perfil Activo ---
# Activa el perfil "dev". Spring Boot buscará y cargará automáticamente
# el archivo "application-dev.properties" para la configuración específica.
spring.profiles.active=prod

# Clave secreta para JWT (JSON Web Tokens) - Guárdala de forma segura
# Puedes mover esto al perfil 'dev' si tienes claves diferentes por entorno.
jwt.secret=mi_clave_secreta_super_segura_para_jwt_123456
jwt.expirationInMs=86400000 
# 24 horas en milisegundos