-- ============================================================
-- V1__init_schema.sql  |  PostgreSQL (Render - Produccion)
-- Crea el esquema completo de SaveUp Lite de forma idempotente.
-- CREATE TABLE IF NOT EXISTS disponible en PostgreSQL 9.1+.
-- ============================================================

-- 3.1 USUARIO
CREATE TABLE IF NOT EXISTS usuario (
    id_usuario      VARCHAR(255)  NOT NULL,
    nombre          VARCHAR(255)  NOT NULL,
    apellido        VARCHAR(255)  NOT NULL,
    email           VARCHAR(255)  NOT NULL,
    contrasena_hash VARCHAR(100)  NOT NULL,
    fecha_registro  TIMESTAMP     NOT NULL,
    CONSTRAINT pk_usuario       PRIMARY KEY (id_usuario),
    CONSTRAINT uq_usuario_email UNIQUE      (email)
);

-- 3.2 CATEGORIA
CREATE TABLE IF NOT EXISTS categoria (
    id_categoria     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre           VARCHAR(255) NOT NULL,
    icon_id          VARCHAR(255),
    color_hex        VARCHAR(20),
    tipo_presupuesto VARCHAR(20),
    CONSTRAINT pk_categoria        PRIMARY KEY (id_categoria),
    CONSTRAINT uq_categoria_nombre UNIQUE      (nombre),
    CONSTRAINT chk_categoria_tipo  CHECK (tipo_presupuesto IN ('NECESIDAD','DESEO','AHORRO','OTROS'))
);

-- 3.4 META_AHORRO (referenciada por MOVIMIENTO)
CREATE TABLE IF NOT EXISTS meta_ahorro (
    id_meta        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre         VARCHAR(100)   NOT NULL,
    monto_objetivo NUMERIC(19, 2),
    monto_actual   NUMERIC(19, 2) DEFAULT 0.00,
    fecha_limite   DATE,
    usuario_id     VARCHAR(255)   NOT NULL,
    CONSTRAINT pk_meta_ahorro  PRIMARY KEY (id_meta),
    CONSTRAINT fk_meta_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id_usuario)
);

-- 3.5 DEUDA (referenciada por MOVIMIENTO)
CREATE TABLE IF NOT EXISTS deuda (
    id_deuda        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre          VARCHAR(100)   NOT NULL,
    descripcion     VARCHAR(255),
    monto_total     NUMERIC(19, 2) NOT NULL,
    cantidad_cuotas INTEGER        NOT NULL,
    estado          VARCHAR(20)    NOT NULL,
    fecha_creacion  TIMESTAMP      NOT NULL,
    usuario_id      VARCHAR(255)   NOT NULL,
    CONSTRAINT pk_deuda        PRIMARY KEY (id_deuda),
    CONSTRAINT fk_deuda_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id_usuario),
    CONSTRAINT chk_deuda_estado CHECK (estado IN ('PENDIENTE','PAGADA','CANCELADA'))
);

-- 3.3 MOVIMIENTO
CREATE TABLE IF NOT EXISTS movimiento (
    id_movimiento   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    monto           NUMERIC(19, 2) NOT NULL,
    descripcion     VARCHAR(100)   NOT NULL,
    fecha           TIMESTAMP      NOT NULL,
    tipo_movimiento VARCHAR(30)    NOT NULL,
    usuario_id      VARCHAR(255)   NOT NULL,
    deuda_id        BIGINT,
    categoria_id    BIGINT,
    meta_id         BIGINT,
    CONSTRAINT pk_movimiento    PRIMARY KEY (id_movimiento),
    CONSTRAINT fk_mov_usuario   FOREIGN KEY (usuario_id)   REFERENCES usuario(id_usuario),
    CONSTRAINT fk_mov_deuda     FOREIGN KEY (deuda_id)     REFERENCES deuda(id_deuda),
    CONSTRAINT fk_mov_categoria FOREIGN KEY (categoria_id) REFERENCES categoria(id_categoria),
    CONSTRAINT fk_mov_meta      FOREIGN KEY (meta_id)      REFERENCES meta_ahorro(id_meta),
    CONSTRAINT chk_mov_tipo     CHECK (tipo_movimiento IN ('INGRESO_GENERAL','GASTO_GENERAL','PAGO_DEUDA','ABONO_META','RETIRO_META'))
);

-- 3.6 CONFIGURACION_PRESUPUESTO
CREATE TABLE IF NOT EXISTS configuracion_presupuesto (
    id_configuracion            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id                  VARCHAR(255)   NOT NULL,
    porcentaje_necesidades      NUMERIC(5, 2)  NOT NULL,
    porcentaje_deseos           NUMERIC(5, 2)  NOT NULL,
    porcentaje_ahorro           NUMERIC(5, 2)  NOT NULL,
    activo                      BOOLEAN        NOT NULL DEFAULT TRUE,
    automatizar_ahorro_en_metas BOOLEAN        NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_conf_presupuesto PRIMARY KEY (id_configuracion),
    CONSTRAINT uq_conf_usuario     UNIQUE      (usuario_id),
    CONSTRAINT fk_conf_usuario     FOREIGN KEY (usuario_id) REFERENCES usuario(id_usuario)
);

-- 3.7 ASIGNACION_META_PRESUPUESTO
CREATE TABLE IF NOT EXISTS asignacion_meta_presupuesto (
    id_asignacion         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    configuracion_id      BIGINT        NOT NULL,
    meta_id               BIGINT        NOT NULL,
    porcentaje_asignacion NUMERIC(5, 2) NOT NULL,
    CONSTRAINT pk_asignacion  PRIMARY KEY (id_asignacion),
    CONSTRAINT fk_asig_config FOREIGN KEY (configuracion_id) REFERENCES configuracion_presupuesto(id_configuracion),
    CONSTRAINT fk_asig_meta   FOREIGN KEY (meta_id)          REFERENCES meta_ahorro(id_meta)
);
