ALTER TABLE DEUDA ADD COLUMN tipo_deuda VARCHAR(50) DEFAULT 'OTRO' NOT NULL;
ALTER TABLE DEUDA ADD COLUMN modalidad_calculo VARCHAR(50) DEFAULT 'SIN_INTERES' NOT NULL;
ALTER TABLE DEUDA ADD COLUMN monto_capital NUMERIC(19,2);
ALTER TABLE DEUDA ADD COLUMN gastos_iniciales NUMERIC(19,2) DEFAULT 0 NOT NULL;
ALTER TABLE DEUDA ADD COLUMN costo_adicional_por_cuota NUMERIC(19,2) DEFAULT 0 NOT NULL;
ALTER TABLE DEUDA ADD COLUMN tasa_mensual NUMERIC(12,8) DEFAULT 0 NOT NULL;
ALTER TABLE DEUDA ADD COLUMN valor_cuota NUMERIC(19,2);
ALTER TABLE DEUDA ADD COLUMN fecha_primera_cuota DATE;
ALTER TABLE DEUDA ADD COLUMN cuotas_pagadas_previas INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE DEUDA ADD COLUMN monto_pagado_previo NUMERIC(19,2) DEFAULT 0 NOT NULL;
ALTER TABLE DEUDA ADD COLUMN carga_anual_equivalente NUMERIC(10,4) DEFAULT 0 NOT NULL;
ALTER TABLE DEUDA ADD COLUMN costo_total_credito NUMERIC(19,2);

ALTER TABLE DEUDA ADD CONSTRAINT chk_tipo_deuda CHECK (tipo_deuda IN ('PERSONAL', 'TIENDA', 'CREDITO_CONSUMO', 'EDUCACION', 'OTRO'));
ALTER TABLE DEUDA ADD CONSTRAINT chk_modalidad_calculo CHECK (modalidad_calculo IN ('SIN_INTERES', 'TASA_CONOCIDA', 'CUOTA_CONOCIDA'));
ALTER TABLE DEUDA ADD CONSTRAINT chk_cuotas_pagadas_previas CHECK (cuotas_pagadas_previas >= 0);

UPDATE DEUDA SET 
    monto_capital = monto_total,
    valor_cuota = ROUND(monto_total / cantidad_cuotas, 2),
    costo_total_credito = monto_total;

ALTER TABLE DEUDA ALTER COLUMN monto_capital SET NOT NULL;
ALTER TABLE DEUDA ALTER COLUMN valor_cuota SET NOT NULL;
ALTER TABLE DEUDA ALTER COLUMN costo_total_credito SET NOT NULL;
